# Generated by Django 2.2.3 on 2019-07-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('description', models.TextField()),
                ('is_offer', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'travello',
                'managed': True,
            },
        ),
    ]
